/**
 * Suggestions for the major field (onboarding A2, Profile > Details). Not a
 * closed list: anything typed is kept. Common US majors and minors, in no
 * school's own naming.
 */
export const MAJORS: readonly string[] = [
  "Accounting",
  "Actuarial Science",
  "Advertising",
  "Aerospace Engineering",
  "African American Studies",
  "Agricultural Science",
  "American Studies",
  "Animation",
  "Anthropology",
  "Applied Mathematics",
  "Applied Physics",
  "Architecture",
  "Art History",
  "Artificial Intelligence",
  "Asian Studies",
  "Astronomy",
  "Astrophysics",
  "Behavioral Neuroscience",
  "Biochemistry",
  "Bioengineering",
  "Bioinformatics",
  "Biology",
  "Biomedical Engineering",
  "Biotechnology",
  "Business Administration",
  "Business Analytics",
  "Chemical Engineering",
  "Chemistry",
  "Civil Engineering",
  "Classics",
  "Cognitive Science",
  "Communication Studies",
  "Comparative Literature",
  "Computational Biology",
  "Computer Engineering",
  "Computer Science",
  "Construction Management",
  "Creative Writing",
  "Criminal Justice",
  "Criminology",
  "Cybersecurity",
  "Dance",
  "Data Science",
  "Dental Hygiene",
  "Design",
  "Digital Media",
  "Early Childhood Education",
  "Earth Science",
  "Ecology",
  "Economics",
  "Education",
  "Electrical Engineering",
  "Elementary Education",
  "Engineering",
  "Engineering Management",
  "English",
  "Entrepreneurship",
  "Environmental Engineering",
  "Environmental Science",
  "Environmental Studies",
  "Exercise Science",
  "Fashion Design",
  "Film Studies",
  "Finance",
  "Fine Arts",
  "Food Science",
  "Forensic Science",
  "French",
  "Game Design",
  "Gender Studies",
  "Geography",
  "Geology",
  "German",
  "Global Studies",
  "Graphic Design",
  "Health Sciences",
  "Health Informatics",
  "History",
  "Hospitality Management",
  "Human Resources",
  "Human-Computer Interaction",
  "Industrial Design",
  "Industrial Engineering",
  "Information Systems",
  "Information Technology",
  "Interior Design",
  "International Business",
  "International Relations",
  "Journalism",
  "Kinesiology",
  "Latin American Studies",
  "Law",
  "Liberal Arts",
  "Linguistics",
  "Management",
  "Management Information Systems",
  "Marine Biology",
  "Marketing",
  "Materials Science",
  "Mathematics",
  "Mechanical Engineering",
  "Media Studies",
  "Medical Laboratory Science",
  "Microbiology",
  "Molecular Biology",
  "Music",
  "Music Technology",
  "Neuroscience",
  "Nursing",
  "Nutrition",
  "Operations Management",
  "Pharmacy",
  "Philosophy",
  "Physical Therapy",
  "Physics",
  "Political Science",
  "Pre-Law",
  "Pre-Med",
  "Product Design",
  "Psychology",
  "Public Health",
  "Public Policy",
  "Public Relations",
  "Real Estate",
  "Religious Studies",
  "Robotics",
  "Social Work",
  "Sociology",
  "Software Engineering",
  "Spanish",
  "Sports Management",
  "Statistics",
  "Supply Chain Management",
  "Sustainability",
  "Theatre",
  "Undeclared",
  "Urban Planning",
  "Video Game Development",
  "Visual Arts",
  "Women's Studies",
  "Zoology",
];

/**
 * Up to `limit` suggestions for what has been typed: words that start with
 * the query first, then any that contain it. Case-insensitive.
 */
export function suggestMajors(query: string, limit = 6, list: readonly string[] = MAJORS): string[] {
  const q = query.trim().toLowerCase();
  if (!q) return [];
  const starts: string[] = [];
  const wordStarts: string[] = [];
  const contains: string[] = [];
  for (const major of list) {
    const m = major.toLowerCase();
    if (m === q) continue;
    if (m.startsWith(q)) starts.push(major);
    else if (m.split(/[\s-]+/).some((w) => w.startsWith(q))) wordStarts.push(major);
    else if (m.includes(q)) contains.push(major);
  }
  return [...starts, ...wordStarts, ...contains].slice(0, limit);
}
