import {
  ArrowLeftRight,
  ArrowRightLeft,
  Banknote,
  Bell,
  Building2,
  CalendarCheck,
  CalendarDays,
  CalendarPlus,
  CalendarRange,
  CalendarSync,
  ChartColumn,
  CheckSquare,
  Columns3,
  Database,
  DatabaseZap,
  FileText,
  FileUp,
  Folder,
  FolderKanban,
  Globe,
  Handshake,
  History,
  Inbox,
  LayoutDashboard,
  ListChecks,
  Mail,
  MailPlus,
  MessageCircleQuestion,
  Monitor,
  Moon,
  Network,
  Newspaper,
  NotebookText,
  Palette,
  PanelLeft,
  Paperclip,
  PiggyBank,
  Pin,
  Plug,
  Receipt,
  Rocket,
  ScrollText,
  Settings,
  Settings2,
  ShieldCheck,
  Sparkles,
  SquarePen,
  Sun,
  Table,
  Tag,
  Tags,
  Trash2,
  TriangleAlert,
  Upload,
  User,
  UserRound,
  Users,
  Wallet,
  type LucideIcon,
} from "lucide-react";

import type { SearchKind } from "@/lib/search/types";

/** The icon of each kind of search result. */
export const KIND_ICONS: Record<SearchKind, LucideIcon> = {
  page: FileText,
  action: Sparkles,
  note: NotebookText,
  folder: Folder,
  file: Paperclip,
  task: CheckSquare,
  project: FolderKanban,
  label: Tag,
  event: CalendarDays,
  poll: CalendarCheck,
  person: User,
  position: Network,
  database: Database,
  transaction: Banknote,
  sponsor: Handshake,
};

/** Icons the page catalog names (catalog.ts, the sidebar sections, settings-nav). */
export const NAMED_ICONS: Record<string, LucideIcon> = {
  ArrowLeftRight,
  ArrowRightLeft,
  Bell,
  Building2,
  CalendarCheck,
  CalendarDays,
  CalendarPlus,
  CalendarRange,
  CalendarSync,
  ChartColumn,
  CheckSquare,
  Columns3,
  Database,
  DatabaseZap,
  FileUp,
  Globe,
  Handshake,
  History,
  Inbox,
  LayoutDashboard,
  ListChecks,
  Mail,
  MailPlus,
  MessageCircleQuestion,
  Monitor,
  Moon,
  Network,
  Newspaper,
  NotebookText,
  Palette,
  PanelLeft,
  Paperclip,
  PiggyBank,
  Pin,
  Plug,
  Receipt,
  Rocket,
  ScrollText,
  Settings,
  Settings2,
  ShieldCheck,
  Sparkles,
  SquarePen,
  Sun,
  Table,
  Tags,
  Trash2,
  TriangleAlert,
  Upload,
  UserRound,
  Users,
  Wallet,
};
